export const ANECDOTE_CHANCHE = 0.1;

export const ANECDOTES_EN = [
  { title: "The Wind Archive", text: "This cliff is known for a strange phenomenon: when the wind blows from the north, it produces a rustling that sounds like pages turning. Scholars believe the sound is actually an ancient elemental language recounting the world’s history before maps existed." },
  { title: "Footsteps of the Shy Giant", text: "Generations ago, a solitary giant walked these hills only at dusk to avoid being seen. His steps were so gentle that nearby villages thought he was a benevolent spirit. On foggy nights, some travelers claim they can still feel a faint trembling under the ground." },
  { title: "The Buried Palace", text: "Beneath this stretch of land lies a palace that once ruled a forgotten dynasty. Its walls sank slowly under sand and roots. Occasionally, fragments of its mosaics surface, as if the palace were trying to remind the world of its existence." },
  { title: "The Disobedient Light", text: "In this clearing, light behaves in peculiar ways: it bounces in impossible directions, illuminating shadows that shouldn’t be there. Some mages think it's a remnant of a failed experiment that attempted to divide the day into more than one morning." },
  { title: "The Frostbound Pact Table", text: "Centuries ago, the leaders of three clans gathered here to sign a pact that shattered at sunrise. The table where they sealed their alliance froze solid within seconds and remains covered in a thin, eternal frost." },
  { title: "The Mirrorless Pond", text: "This still pool of water reflects nothing—not sky, not trees, not travelers. Yet those who stare long enough swear they see glimpses of distant lands, like fleeting windows into parallel worlds." },
  { title: "The Campfire Library", text: "A wandering explorer once set up a makeshift library here, built of crates, ropes and dried leaves. He shared his stories with anyone who stopped by. When he left, he wrote: 'The books go with me, but the stories stay in the air.' Some say you can still hear his tales in the breeze." },
  { title: "The Duel That Never Began", text: "Two rival swordsmen stood here at dawn to settle their feud. Yet neither struck a blow. Hours passed as they stared each other down, until both vanished without leaving footprints. The field remains unnervingly quiet, as if waiting for their first move." },
  { title: "Harvest of Shadows", text: "Farmers once claimed they could gather 'ripe shadows' from between the trees each autumn, using them to ward off ill omens. On moonless nights, some travelers insist they see loose shadows drifting back toward their trees." },
  { title: "The Singing Roots", text: "Beneath these rocks grows a kind of root that hums low notes whenever the earth vibrates. Long ago, villagers listened to these tones to predict storms or the movement of underground beasts. Only attentive wanderers hear them now." },
  { title: "The Path That Moved Itself", text: "During an ancient war, an army tried to secure this route for supply caravans. But something—or someone—altered the trail overnight, twisting it into new shapes each morning. Since then, the terrain seems to retain a faint rebellious instability." },
  { title: "The Well of Three Truths", text: "Legend says that anyone who tosses a coin into this well hears three whispers: one from the past, one from the present, and one from the future. Few share what they heard, and most advise against listening to the third voice." },
  { title: "The Inverted Camp", text: "The remains of a camp lie oddly arranged: pots hooked to trees, blankets buried, campfires set atop boulders. No one knows who lived here or why they arranged their belongings this way. Everything appears untouched—just… reorganized by a very different mind." },
  { title: "The Guardian Who Would Not Wake", text: "An ancient protector of the realm was buried beneath this hill, so honorable that local spirits vowed to watch over his rest. Travelers often feel a silent gaze upon them, as if he still judges the intentions of those who pass." },
  { title: "The Thinking Echo Chamber", text: "In this natural cavern, echoes return with a slight variation, almost as though considering each word before repeating it. Local bards visit to refine their melodies, claiming the chamber preserves fragments of forgotten songs." },
  { title: "The Invisible Herd", text: "Decades ago, a shepherd insisted his flock was so well-trained he could guide them with only his thoughts. One day, the animals vanished without a trace. Since then, faint bleats can sometimes be heard at night—though no creatures are ever seen." },
  { title: "The Silent Workshop", text: "An artisan worked here crafting tiny mechanisms of uncanny precision. His final projects remain unfinished, abandoned when he quietly disappeared. Though his tools rusted long ago, some pieces seem to shift very slightly when unobserved." },
  { title: "The Forest That Bargains", text: "Nomadic tribes believed this forest had a will of its own, asking a small tribute from travelers—a stone, a flower, a whispered promise—in exchange for safe passage. Those who ignored the custom claimed to walk in circles for days." },
  { title: "The Luminous Fissure", text: "A thin crack in the rock emits a steady blue glow with no natural explanation. Alchemists believe it's a leak of ancient arcane energy, perhaps from a magical network buried deep beneath the surface." },
  { title: "The Circle Where Time Misbehaves", text: "An explorer once found a ring of stones where moss never grows and fallen leaves never decay. Decades later, he returned to find it unchanged. He claimed time inside the circle flows differently—or perhaps doesn’t flow at all." }
];

export const ANECDOTES_ES = [
  { title: "El Archivo del Viento", text: "Este acantilado es conocido por un extraño fenómeno: cuando el viento sopla desde el norte, produce un susurro que suena como páginas pasando. Los eruditos creen que el sonido es en realidad un antiguo lenguaje elemental que narra la historia del mundo antes de que existieran los mapas." },
  { title: "Las Huellas del Gigante Tímido", text: "Hace generaciones, un gigante solitario caminaba por estas colinas solo al atardecer para evitar ser visto. Sus pasos eran tan suaves que los pueblos cercanos pensaban que era un espíritu benévolo. En noches de niebla, algunos viajeros afirman que aún sienten un leve temblor bajo el suelo." },
  { title: "El Palacio Enterrado", text: "Bajo este tramo de tierra yace un palacio que una vez gobernó una dinastía olvidada. Sus muros se hundieron lentamente bajo la arena y las raíces. Ocasionalmente, fragmentos de sus mosaicos emergen, como si el palacio intentara recordar al mundo su existencia." },
  { title: "La Luz Desobediente", text: "En este claro, la luz se comporta de formas peculiares: rebota en direcciones imposibles, iluminando sombras que no deberían estar allí. Algunos magos piensan que es el remanente de un experimento fallido que intentó dividir el día en más de una mañana." },
  { title: "La Mesa del Pacto Helado", text: "Hace siglos, los líderes de tres clanes se reunieron aquí para firmar un pacto que se rompió al amanecer. La mesa donde sellaron su alianza se congeló en segundos y permanece cubierta por una escarcha eterna." },
  { title: "El Estanque Sin Reflejo", text: "Esta tranquila poza de agua no refleja nada: ni cielo, ni árboles, ni viajeros. Sin embargo, quienes miran el tiempo suficiente juran ver destellos de tierras distantes, como ventanas fugaces a mundos paralelos." },
  { title: "La Biblioteca de la Fogata", text: "Un explorador errante montó aquí una biblioteca improvisada, hecha de cajas, cuerdas y hojas secas. Compartía sus historias con quien se acercara. Al irse, escribió: 'Los libros se van conmigo, pero las historias quedan en el aire.' Algunos dicen que aún se escuchan sus relatos en la brisa." },
  { title: "El Duelo Que Nunca Comenzó", text: "Dos espadachines rivales se pararon aquí al amanecer para resolver su disputa. Sin embargo, ninguno atacó. Pasaron horas mirándose hasta que ambos desaparecieron sin dejar huellas. El campo permanece inquietantemente silencioso, como si esperara su primer movimiento." },
  { title: "La Cosecha de Sombras", text: "Los campesinos decían que podían recolectar 'sombras maduras' entre los árboles cada otoño, usándolas para alejar malos augurios. En noches sin luna, algunos viajeros insisten en ver sombras sueltas regresando a sus árboles." },
  { title: "Las Raíces Cantoras", text: "Bajo estas rocas crece una raíz que emite notas graves cuando la tierra vibra. Hace mucho, los aldeanos escuchaban estos tonos para predecir tormentas o el movimiento de bestias subterráneas. Solo los viajeros atentos las oyen ahora." },
  { title: "El Camino Que Se Movía Solo", text: "Durante una guerra antigua, un ejército intentó asegurar esta ruta para caravanas de suministros. Pero algo—o alguien—alteraba el sendero cada noche, retorciéndolo en nuevas formas cada mañana. Desde entonces, el terreno parece conservar una leve inestabilidad rebelde." },
  { title: "El Pozo de las Tres Verdades", text: "La leyenda dice que quien arroja una moneda en este pozo escucha tres susurros: uno del pasado, uno del presente y uno del futuro. Pocos comparten lo que oyeron, y la mayoría aconseja no escuchar la tercera voz." },
  { title: "El Campamento Invertido", text: "Los restos de un campamento están dispuestos de forma extraña: ollas colgadas en árboles, mantas enterradas, fogatas sobre rocas. Nadie sabe quién vivió aquí ni por qué organizó sus pertenencias así. Todo parece intacto—solo… reorganizado por una mente muy diferente." },
  { title: "El Guardián Que No Quiso Despertar", text: "Un antiguo protector del reino fue enterrado bajo esta colina, tan honorable que los espíritus locales prometieron vigilar su descanso. Los viajeros suelen sentir una mirada silenciosa, como si aún juzgara las intenciones de quienes pasan." },
  { title: "La Cámara del Eco Pensante", text: "En esta caverna natural, los ecos regresan con una ligera variación, como si consideraran cada palabra antes de repetirla. Los bardos locales la visitan para perfeccionar sus melodías, asegurando que la cámara conserva fragmentos de canciones olvidadas." },
  { title: "El Rebaño Invisible", text: "Hace décadas, un pastor insistía en que su rebaño estaba tan bien entrenado que podía guiarlos solo con el pensamiento. Un día, los animales desaparecieron sin dejar rastro. Desde entonces, a veces se oyen balidos por la noche—pero nunca se ven criaturas." },
  { title: "El Taller Silencioso", text: "Un artesano trabajaba aquí creando mecanismos diminutos de precisión asombrosa. Sus últimos proyectos quedaron inconclusos, abandonados cuando desapareció silenciosamente. Aunque sus herramientas se oxidaron hace mucho, algunas piezas parecen moverse levemente cuando no se las observa." },
  { title: "El Bosque Que Negocia", text: "Las tribus nómadas creían que este bosque tenía voluntad propia, pidiendo un pequeño tributo a los viajeros—una piedra, una flor, una promesa susurrada—a cambio de un paso seguro. Quienes ignoraban la costumbre decían caminar en círculos durante días." },
  { title: "La Fisura Luminosa", text: "Una delgada grieta en la roca emite un resplandor azul constante sin explicación natural. Los alquimistas creen que es una fuga de energía arcana antigua, quizá de una red mágica enterrada bajo la superficie." },
  { title: "El Círculo Donde el Tiempo Se Porta Mal", text: "Un explorador encontró un círculo de piedras donde nunca crece musgo ni se descomponen las hojas caídas. Décadas después, regresó y lo halló igual. Aseguraba que el tiempo dentro del círculo fluye diferente—o quizá no fluye en absoluto." }
];
